### ISSUE TITLE
Paginate PoP Payouts Response

### ISSUE THREAD

**Issue by ClaytonNorthey92** [hemilabs/heminetwork#195] opened 2024-08-02 16:02 UTC
### Confirmation

- [X] I have checked for similar issues.

### Problem

When op-node requests pop payouts, we need to paginate because this response is large and will not scale.

If I am not mistaken, this will require pagination in both bss and bfg getting pop payouts responses.

### Suggested solution

paginate bss and bfg pop payouts/pop tx responses when op node requests them

**Comment by joshuasing** [comment] 2024-08-05 12:58
@ClaytonNorthey92 Is this a duplicate of, or similar to #193?

**Comment by ClaytonNorthey92** [comment] 2024-08-05 15:07
hey @joshuasing it's a duplicate essentially, the only difference is that I added the pagination through BSS as well (so the full call path op-node -> bss -> bfg can be paginated)

**Comment by Syuraih7** [comment] 2024-08-14 14:12
i already clear all task but helmi pilot cant verify my action

**Closed** 2024-10-10 13:47 UTC
Labels: type: enhancement, status: in review, area: bfg, area: bss
